script: bundle exec rake spec

matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: jruby
    - rvm: rbx
    - rvm: ree

notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    urls:
      - http://dx-helper.herokuapp.com/travis

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby
  - rbx
  - ree
