language: ruby

sudo: false

before_install:
  - gem install "rubygems-update:<3.0.0" --no-document
  - update_rubygems
  - gem update --system
  - gem install bundler

after_success:
  - bundle exec codeclimate-test-reporter

script: bundle exec rake spec
cache: bundler
bundler_args: --without development

rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
env:
  global:
    secure: IKoaAfTsrU1scmRO7LNJ+hVGzVeYrCB8qwr1KK/WiCm6JirAhiwvpf7osaMT6h+QRELSiAay2wPn89FqpZ9wzpL/zh5kpgfI04gnKrD7ZlPiKDPYddt6R4+Z4+LUZ0dkoM//MjRiIKz0wdvgbzn/E8FSpuhh3FeVYzYVTmAfgME=
